# note: currently broken, working on it
# todo: fix "connection refused" issue - not k8s issue, issue when building dockerimage? maybe has to do with exposed ports
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  selector:
    matchLabels:
      app: broker
  replicas: 1
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: stevenewald/cascade_broker 
        ports:
        - containerPort: 50050 

